export const ADD_EXPENSE_TYPE = 'ADD_EXPENSE_TYPE';
export const GET_EXPENSES_TYPES_FROM_STORAGE = 'GET_EXPENSES_TYPES_FROM_STORAGE';
export const AGREGAR_GASTO = 'AGREGAR_GASTO';
export const CARGAR_GASTOS = 'CARGAR_GASTOS';
export const SELECCIONAR_CATEGORIA = 'SELECCIONAR_CATEGORIA';
export const GET_EXPENSES_LIST_FROM_STORAGE = 'GET_EXPENSES_LIST_FROM_STORAGE';